export const allSkills = [
  // 🖥️ Technical Skills
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "Node.js",
  "Express.js",
  "Python",
  "Django",
  "Flask",
  "FastAPI",
  "Java",
  "Spring Boot",
  "Kotlin",
  "C#",
  ".NET",
  "C++",
  "Go",
  "Rust",
  "PHP",
  "Laravel",
  "Ruby",
  "Ruby on Rails",
  "SQL",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Firebase",
  "GraphQL",
  "REST APIs",
  "gRPC",
  "WebSockets",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Jenkins",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Terraform",
  "Linux",
  "Bash/Shell Scripting",
  "Web Security",
  "Penetration Testing",
  "Ethical Hacking",
  "Blockchain",
  "Solidity",
  "Smart Contracts",
  "AI/ML",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "Data Structures & Algorithms",
  "Data Analysis",
  "Data Engineering",
  "Data Visualization",
  "Power BI",
  "Tableau",
  "Snowflake",
  "ETL Pipelines",
  "BigQuery",
  "Hadoop",
  "Spark",
  "Testing",
  "Jest",
  "Cypress",
  "Playwright",
  "Selenium",
  "Unit Testing",
  "Integration Testing",
  "Automation Testing",
  "Performance Testing",

  // 🎨 Creative & Design Skills
  "UI Design",
  "UX Design",
  "Figma",
  "Sketch",
  "Adobe XD",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Canva",
  "Motion Design",
  "2D Animation",
  "3D Animation",
  "Cinema 4D",
  "Blender",
  "After Effects",
  "Premiere Pro",
  "Video Editing",
  "Photo Editing",
  "Graphic Design",
  "Branding",
  "Typography",
  "Illustration",
  "Wireframing",
  "Prototyping",
  "User Research",
  "A/B Testing",

  // 📈 Marketing & Growth
  "Digital Marketing",
  "SEO",
  "SEM",
  "Google Ads",
  "Facebook Ads",
  "Email Marketing",
  "Marketing Automation",
  "Copywriting",
  "Content Strategy",
  "Content Writing",
  "Blogging",
  "Influencer Marketing",
  "Social Media Marketing",
  "Social Media Management",
  "Growth Hacking",
  "Analytics",
  "Google Analytics",
  "Conversion Rate Optimization (CRO)",
  "CRM",
  "HubSpot",
  "Salesforce",

  // 💬 Communication & Management
  "Project Management",
  "Agile",
  "Scrum",
  "Kanban",
  "JIRA",
  "Trello",
  "Asana",
  "Notion",
  "ClickUp",
  "Confluence",
  "Team Leadership",
  "Stakeholder Management",
  "Client Communication",
  "Conflict Resolution",
  "Public Speaking",
  "Presentation Skills",
  "Technical Writing",
  "Documentation",
  "Time Management",
  "Remote Work Tools",
  "Slack",
  "Zoom",
  "MS Teams",
  "Notion",
  "Google Workspace",
  "Microsoft Office",
  "Excel",
  "Word",
  "PowerPoint",

  // 📚 Education & Training
  "Instructional Design",
  "Curriculum Development",
  "Online Teaching",
  "Workshop Facilitation",
  "LMS (Learning Management Systems)",
  "Corporate Training",
  "eLearning Tools",
  "Assessment Design",

  // 💼 Business & Operations
  "Business Strategy",
  "Market Research",
  "Product Management",
  "Product Roadmapping",
  "User Story Mapping",
  "OKRs",
  "KPI Tracking",
  "Budgeting",
  "Operations Management",
  "Supply Chain Management",
  "Logistics",
  "Business Intelligence",
  "Financial Modeling",
  "Accounting",
  "QuickBooks",
  "Tally",
  "ERP Systems",

  // 🔐 Legal & Compliance
  "Contract Management",
  "GDPR Compliance",
  "Intellectual Property",
  "Risk Management",
  "Internal Auditing",
  "Policy Writing",

  // 🧠 Soft Skills
  "Problem Solving",
  "Critical Thinking",
  "Adaptability",
  "Creativity",
  "Teamwork",
  "Empathy",
  "Emotional Intelligence",
  "Initiative",
  "Accountability",
  "Attention to Detail",

  // 🧪 Scientific & R&D
  "Lab Equipment Handling",
  "Scientific Research",
  "Clinical Trials",
  "Chemistry Knowledge",
  "Biotech Research",
  "Data Interpretation",

  // 🛠️ Trades & Physical Skills
  "Carpentry",
  "Plumbing",
  "Welding",
  "Electrician Work",
  "HVAC",
  "Mechanics",
  "Blueprint Reading",
  "Machine Operation",
  "Forklift Driving",

  // 🎭 Media, Arts, Entertainment
  "Acting",
  "Voice-over",
  "Scriptwriting",
  "Music Production",
  "DJing",
  "Sound Design",
  "Game Design",
  "Level Design",
  "Game Development",
  "Unity",
  "Unreal Engine",

  // 🛍️ Sales & Customer-Facing
  "Sales Strategy",
  "Lead Generation",
  "CRM Tools",
  "Cold Calling",
  "Customer Support",
  "Technical Support",
  "Live Chat Support",
  "POS Systems",
  "Upselling & Cross-selling",

  // 🏥 Healthcare & Wellness
  "Patient Care",
  "Medical Terminology",
  "Clinical Documentation",
  "Nutrition Planning",
  "Mental Health Counseling",
  "Yoga Instruction",
  "Fitness Training",

  // 🧳 Hospitality & Travel
  "Event Planning",
  "Guest Services",
  "Reservation Management",
  "Food Safety",
  "Bartending",
  "Housekeeping",
  "Tour Guiding",
  "Flight Booking Systems",

  // 🌍 Languages
  "English (Fluent)",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Arabic",
  "Hindi",
  "Japanese",
  "Korean",
  "Translation",
  "Interpretation",
  "Sign Language",

  // 🧑‍💼 HR & Recruiting
  "Recruiting",
  "Interviewing",
  "Onboarding",
  "HRIS Systems",
  "Employee Engagement",
  "Payroll Management",

  // 🤖 DevOps & SRE
  "Infrastructure as Code",
  "Monitoring Tools (Prometheus, Grafana)",
  "Incident Management",
  "SLA/SLO Definition",
  "Observability",
  "Logging (ELK, Loki)",

  // 🌐 Web3 & Crypto
  "NFT Design",
  "DApp Development",
  "Ethereum",
  "Solana",
  "Metamask Integration",
  "DeFi Protocols",

  // 📦 E-commerce
  "Shopify",
  "WooCommerce",
  "Magento",
  "Product Listing",
  "Inventory Management",
  "Order Fulfillment",

  // 💡 Misc
  "Creative Writing",
  "Voice Modulation",
  "Podcast Editing",
  "3D Printing",
  "Drone Operation",
  "Typing (WPM)",
  "Speed Reading",
  "Handwriting Analysis",
  "Mind Mapping",
];
